### ISSUE TITLE
Freight Performance

### ISSUE THREAD

**Issue by sts** [rcrowley/freight#35] opened 2013-06-05 16:57 UTC
Generating the freight-cache from a source directory with a lot of packages, requires significant CPU resources for generating the MD5/SHA1/SHA256 checksums.

Freight is part of our build process and we would like to reduce the time needed to provide a installable package.

The proposed patch in pull-request #34 will cache the checksums, each in a single file once generated:

```
/srv/freight-source/apt/production/package_1.0_all.deb
/srv/freight-source/apt/production/package_1.0_all.deb.md5
/srv/freight-source/apt/production/package_1.0_all.deb.sha1
/srv/freight-source/apt/production/package_1.0_all.deb.sha256 
```

RFC

**Comment by rcrowley** [comment] 2013-06-22 18:56
Duplicate of #34.

**Closed as completed by rcrowley** 2013-06-22 18:56 UTC
